export const SET_FILTER_EXISTING = "SET_FILTER_EXISTING";
export const SET_FILTER_TYPES = "SET_FILTER_TYPES";
export const RESET_FORMS_FILTER = "RESET_FORMS_FILTER";
export const SET_FORMS_ORDER = "SET_FORMS_ORDER";
export const SET_FORMS_CREATE_TYPES = "SET_FORMS_CREATE_TYPES";
